import { AnimatePresence, motion } from "framer-motion";
import { X, ShieldCheck, Bug, Users, Activity, Printer } from "lucide-react";
import { cn } from "@/lib/utils";
import logo from "@/assets/goat2.png";
import { Tag, type TagTone } from "./shell";
import { useLanguage } from "@/i18n/LanguageContext";
import { formatDateTime } from "@/lib/format";

type Copy = {
  reportTitle: string;
  exportPdf: string;
  closeAria: string;
  onlineStatus: string;
  offlineStatus: string;
  onlinePlayers: string;
  detections: string;
  activeBans: string;
  health: string;
  punishmentDistribution: string;
  ban: string;
  kick: string;
  flag: string;
  latestDetections: string;
  noDetections: string;
  footer: string;
};

const pt: Copy = {
  reportTitle: "Relatório de Segurança",
  exportPdf: "Exportar PDF",
  closeAria: "Fechar",
  onlineStatus: "Infraestrutura operacional no momento da geração",
  offlineStatus: "Servidor offline no momento da geração",
  onlinePlayers: "Jogadores Online",
  detections: "Detecções",
  activeBans: "Banimentos Ativos",
  health: "Saúde (Watchdog)",
  punishmentDistribution: "Distribuição de punições recentes",
  ban: "Ban",
  kick: "Kick",
  flag: "Flag",
  latestDetections: "Últimas detecções",
  noDetections: "Nenhuma detecção registrada.",
  footer: "Gerado automaticamente pelo GOAT Anticheat",
};

const en: Copy = {
  reportTitle: "Security Report",
  exportPdf: "Export PDF",
  closeAria: "Close",
  onlineStatus: "Infrastructure operational at time of generation",
  offlineStatus: "Server offline at time of generation",
  onlinePlayers: "Online Players",
  detections: "Detections",
  activeBans: "Active Bans",
  health: "Health (Watchdog)",
  punishmentDistribution: "Recent punishment distribution",
  ban: "Ban",
  kick: "Kick",
  flag: "Flag",
  latestDetections: "Latest detections",
  noDetections: "No detections recorded.",
  footer: "Automatically generated by GOAT Anticheat",
};

type ReportDetection = {
  id: string;
  player: string;
  reason: string;
  time: string;
  confidence: number;
  punishment: string;
};

export interface SecurityReportData {
  serverName: string;
  isOnline: boolean;
  players: number;
  detectionsCount: number;
  bansCount: number;
  healthText: string;
  healthDesc: string;
  detections: ReportDetection[];
}

function punishmentTone(punishment: string): TagTone {
  const p = (punishment || "").toLowerCase();
  if (p.includes("ban")) return "critical";
  if (p.includes("kick")) return "warning";
  if (p.includes("flag")) return "gold";
  return "neutral";
}

function KpiCard({
  icon: Icon,
  label,
  value,
  hint,
  index,
}: {
  icon: typeof Users;
  label: string;
  value: string;
  hint?: string;
  index: number;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35, delay: 0.1 + index * 0.06, ease: [0.22, 1, 0.36, 1] }}
      className="rounded-xl border border-border bg-card p-5"
    >
      <div className="flex items-start justify-between">
        <p className="flex items-center gap-1.5 font-mono text-[10px] tracking-[0.1em] text-muted-foreground uppercase">
          <span className="h-[3px] w-[3px] rounded-[1px] bg-gold/70" />
          {label}
        </p>
        <span className="grid h-7 w-7 shrink-0 place-items-center rounded-[6px] border border-hairline text-foreground/70">
          <Icon className="h-3.5 w-3.5" />
        </span>
      </div>
      <p className="mt-4 text-[24px] font-semibold leading-none tracking-tight tabular-nums">
        {value}
      </p>
      {hint && <p className="mt-2 text-[11px] text-muted-foreground">{hint}</p>}
    </motion.div>
  );
}

export function SecurityReportModal({
  open,
  onClose,
  data,
}: {
  open: boolean;
  onClose: () => void;
  data: SecurityReportData;
}) {
  const { lang } = useLanguage();
  const t = lang === "pt" ? pt : en;
  const tally = data.detections.reduce(
    (acc, d) => {
      const tone = punishmentTone(d.punishment);
      acc[tone] = (acc[tone] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>,
  );
  const total = data.detections.length || 1;

  return (
    <AnimatePresence>
      {open && (
        <div className="fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto p-4 py-10">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="goat-report-no-print fixed inset-0 bg-background/80 backdrop-blur-sm"
          />
          <motion.div
            initial={{ opacity: 0, y: 16, scale: 0.98 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 16, scale: 0.98 }}
            transition={{ duration: 0.25, ease: [0.22, 1, 0.36, 1] }}
            className="goat-report-print relative w-full max-w-3xl overflow-hidden rounded-2xl border border-border bg-background shadow-2xl"
          >
            <div className="flex items-center justify-between border-b border-border bg-card/60 px-7 py-5">
              <div className="flex items-center gap-3">
                <img src={logo} alt="GOAT" className="h-6 w-auto" />
                <div className="h-6 w-px bg-hairline" />
                <div>
                  <p className="font-mono text-[10px] tracking-[0.12em] text-gold uppercase">
                    {t.reportTitle}
                  </p>
                  <p className="text-[11px] text-muted-foreground">
                    {data.serverName} · {formatDateTime(new Date(), lang)}
                  </p>
                </div>
              </div>
              <div className="goat-report-no-print flex items-center gap-2">
                <button
                  onClick={() => window.print()}
                  className="flex items-center gap-1.5 rounded-lg border border-gold/30 bg-gold/10 px-3 py-1.5 text-[12px] font-medium text-gold transition-colors hover:border-gold/50 hover:bg-gold/15"
                >
                  <Printer className="h-3.5 w-3.5" />
                  {t.exportPdf}
                </button>
                <button
                  onClick={onClose}
                  aria-label={t.closeAria}
                  className="grid h-8 w-8 place-items-center rounded-md text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
                >
                  <X className="h-4 w-4" />
                </button>
              </div>
            </div>

            <div className="goat-report-body max-h-[75vh] overflow-y-auto px-7 py-6">
              <motion.div
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3 }}
                className="mb-5 flex items-center gap-2"
              >
                <span
                  className={cn(
                    "h-1.5 w-1.5 rounded-full",
                    data.isOnline
                      ? "bg-emerald-500 shadow-[0_0_6px_rgba(16,185,129,0.6)] animate-pulse"
                      : "bg-red-500",
                  )}
                />
                <p className="text-[13px] text-muted-foreground">
                  {data.isOnline ? t.onlineStatus : t.offlineStatus}
                </p>
              </motion.div>

              <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                <KpiCard
                  icon={Users}
                  label="Jogadores Online"
                  value={String(data.players)}
                  index={0}
                />
                <KpiCard
                  icon={Bug}
                  label="Detecções"
                  value={String(data.detectionsCount)}
                  index={1}
                />
                <KpiCard
                  icon={ShieldCheck}
                  label="Banimentos Ativos"
                  value={String(data.bansCount)}
                  index={2}
                />
                <KpiCard
                  icon={Activity}
                  label="Saúde (Watchdog)"
                  value={data.healthText}
                  hint={data.healthDesc}
                  index={3}
                />
              </div>

              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.35, delay: 0.34 }}
                className="mt-5 rounded-xl border border-border bg-card p-5"
              >
                <p className="mb-3 flex items-center gap-1.5 font-mono text-[10px] tracking-[0.1em] text-muted-foreground uppercase">
                  <span className="h-[3px] w-[3px] rounded-[1px] bg-gold/70" />
                  Distribuição de punições recentes
                </p>
                <div className="flex h-2 overflow-hidden rounded-full bg-accent">
                  {(["critical", "warning", "gold", "neutral"] as const).map((tone) => {
                    const count = tally[tone] || 0;
                    if (!count) return null;
                    const width = (count / total) * 100;
                    const color =
                      tone === "critical"
                        ? "bg-red-500"
                        : tone === "warning"
                          ? "bg-amber-400"
                          : tone === "gold"
                            ? "bg-gold"
                            : "bg-muted-foreground";
                    return (
                      <motion.span
                        key={tone}
                        initial={{ width: 0 }}
                        animate={{ width: `${width}%` }}
                        transition={{ duration: 0.6, delay: 0.4 }}
                        className={color}
                      />
                    );
                  })}
                </div>
                <div className="mt-3 flex flex-wrap gap-4 text-[11.5px] text-muted-foreground">
                  <span className="flex items-center gap-1.5">
                    <span className="h-1.5 w-1.5 rounded-full bg-red-500" /> Ban ·{" "}
                    {tally.critical || 0}
                  </span>
                  <span className="flex items-center gap-1.5">
                    <span className="h-1.5 w-1.5 rounded-full bg-amber-400" /> Kick ·{" "}
                    {tally.warning || 0}
                  </span>
                  <span className="flex items-center gap-1.5">
                    <span className="h-1.5 w-1.5 rounded-full bg-gold" /> Flag · {tally.gold || 0}
                  </span>
                </div>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.35, delay: 0.42 }}
                className="mt-5 rounded-xl border border-border bg-card p-5"
              >
                <p className="mb-3 flex items-center gap-1.5 font-mono text-[10px] tracking-[0.1em] text-muted-foreground uppercase">
                  <span className="h-[3px] w-[3px] rounded-[1px] bg-gold/70" />
                  Últimas detecções
                </p>
                {data.detections.length === 0 ? (
                  <p className="py-4 text-center text-[12px] text-muted-foreground">
                    Nenhuma detecção registrada.
                  </p>
                ) : (
                  <div className="space-y-3">
                    {data.detections.slice(0, 10).map((d) => (
                      <div
                        key={d.id}
                        className="flex items-center justify-between border-b border-border/50 pb-3 last:border-0 last:pb-0"
                      >
                        <div className="min-w-0">
                          <p className="truncate text-[12.5px] font-medium">{d.player}</p>
                          <p className="text-[11px] text-muted-foreground">
                            {d.reason} · {d.time}
                          </p>
                        </div>
                        <Tag tone={punishmentTone(d.punishment)}>{d.punishment}</Tag>
                      </div>
                    ))}
                  </div>
                )}
              </motion.div>

              <p className="mt-6 text-center font-mono text-[9.5px] tracking-[0.1em] text-muted-foreground/50 uppercase">
                Gerado automaticamente pelo GOAT Anticheat
              </p>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
